# Generated by Django 5.2.3 on 2025-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_profile_picture_employee_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مكان العمل'),
        ),
    ]
