# Generated by Django 5.2.3 on 2025-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الغياب'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='excused_absence',
            field=models.BooleanField(blank=True, null=True, verbose_name='غياب بعذر'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='غائب'),
        ),
    ]
