# Generated by Django 5.1.2 on 2025-06-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_expensecategory_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='الصورة الشخصية'),
        ),
    ]
