"""
Django settings for employee_mgmt project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!




SECRET_KEY   = os.environ['SECRET_KEY']
DEBUG        = os.environ.get('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')




# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employees',
    'widget_tweaks',
    'django_countries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'employee_mgmt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'employee_mgmt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True

USE_L10N = True
LOCALE_PATHS = [BASE_DIR / 'locale']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "لوحة الإدارة - نظام الموظفين",
    "site_header": "إدارة النظام",
    "site_brand": "نظام الموظفين",
    "site_logo": None,
    "welcome_sign": "مرحباً بك في لوحة الإدارة",
    "copyright": "جميع الحقوق محفوظة",
    "search_model": ["employees.Employee", "employees.Expense", "employees.Payroll"],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "language_chooser": True,
   
    "custom_js": None,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "order_with_respect_to": ["employees", "auth"],
    "icons": {
        "auth": "fas fa-users-cog",
        "employees.Employee": "fas fa-user-tie",
        "employees.Expense": "fas fa-wallet",
        "employees.Payroll": "fas fa-money-check-alt",
        "employees.Attendance": "fas fa-calendar-check",
        "employees.ExpenseCategory": "fas fa-list-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_links": {},
    "show_ui_builder": False,
    "site_logo_classes": "img-circle",
    "site_logo_dark": None,
    "site_logo_light": None,
    "site_logo_icon": None,
    "site_logo_icon_classes": "",
    "site_logo_icon_dark": None,
    "site_logo_icon_light": None,
    "site_logo_icon_alt": None,
    "site_logo_icon_alt_classes": "",
    "site_logo_icon_alt_dark": None,
    "site_logo_icon_alt_light": None,
    "site_logo_icon_alt_title": None,
    "site_logo_icon_alt_title_classes": "",
    "site_logo_icon_alt_title_dark": None,
    "site_logo_icon_alt_title_light": None,
    "site_logo_icon_alt_title_text": None,
    "site_logo_icon_alt_title_text_classes": "",
    "site_logo_icon_alt_title_text_dark": None,
    "site_logo_icon_alt_title_text_light": None,
    "site_logo_icon_alt_title_text_alt": None,
    "site_logo_icon_alt_title_text_alt_classes": "",
    "site_logo_icon_alt_title_text_alt_dark": None,
    "site_logo_icon_alt_title_text_alt_light": None,
    "site_logo_icon_alt_title_text_alt_alt": None,
    "site_logo_icon_alt_title_text_alt_alt_classes": "",
    "site_logo_icon_alt_title_text_alt_alt_alt_dark": None,
    "site_logo_icon_alt_title_text_alt_alt_alt_light": None,
    "site_logo_icon_alt_title_text_alt_alt_alt_alt": None,
    "site_logo_icon_alt_title_text_alt_alt_alt_alt_classes": "",
    "site_logo_icon_alt_title_text_alt_alt_alt_alt_dark": None,
    "site_logo_icon_alt_title_text_alt_alt_alt_alt_light": None,
    "site_logo_icon_alt_title_text_alt_alt_alt_alt_alt": None,
    "site_logo_icon_alt_title_text_alt_alt_alt_alt_alt_classes": "",
    "site_logo_icon_alt_title_text_alt_alt_alt_alt_alt_dark": None,
    "site_logo_icon_alt_title_text_alt_alt_alt_alt_alt_light": None,
    "custom_css": None,
}

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_HSTS_SECONDS = 3600
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_SSL_REDIRECT = True
